import "@/styles/globals.css"
import type { FC } from "react"
import { TRPCProvider } from "./trpc/client"
type RootLayoutProps = {
  children: React.ReactNode
}

export const metadata = {
  title: "Sample",
  description: "Generated by create next app"
}

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body className="">
        <TRPCProvider>{props.children}</TRPCProvider>
      </body>
    </html>
  )
}

export default RootLayout
